### ISSUE TITLE
Invalid array length when encountering _ in identifier

### ISSUE THREAD

**Issue by richardsimko** [gruntjs/grunt-contrib-jshint#242]
If I have a file that uses _ in an identifier jshint complains. However the error it returns to the reporter does not have `character` defined. This means that the task fails on the line 117 in tasks/lib/jshint.js. I suggest adding a guard along the lines of:

```
(e.character ? grunt.util.repeat(e.character - 1, ' '): '')
```

Here is a sample file:

```
var test = {
    test_test: 'test'
};
```

Also it requires a .jshintrc with `camelcase` set to `true`

Gruntfile config:

```
jshint: {
      all: ['test.js'],
      options: {
        jshintrc: true
      }
}
```

**Comment by AMoo-Miki** [comment]
gruntjs/grunt-contrib-jshint is trusting that jshint will provide a numeric `e.character`, which jshint doesn't always due to a [misdiagnosed bug](https://github.com/jshint/jshint/issues/2778).

If we decide to validate `e.character`, then we should not trust anything jshint gives us and check `e.evidence` and `e.line` before using them.

**Comment by lukasgurschler** [comment]
Im having the same problem because in a Project i have to provide data via ajax to a unchangeable post var like tx_test_modulename. my grunt task fails because of the jshint errror. how can i solve or ignore this?

**Comment by tadas-s** [comment]
Removing [camelcase](http://jshint.com/docs/options/#camelcase) option from `.jshintrc` fixed this for me. It is deprecated / out of jshint scope anyway.

**Comment by XhmikosR** [comment]
This should be fixed upstream.
