### ISSUE TITLE
latedef: 'nofunc' not working in options

### ISSUE THREAD

**Issue by wlanni** [gruntjs/grunt-contrib-jshint#253]
Hello,

I just updated to most recent grunt-contrib-jshint, and the latedef: 'nofunc' setting stopped working.

grunt: 0.4.5
grunt-contrib-jshint: 1.0.0

I've tried three fixes. The only one that worked was updating the .jshintrc. However, we've got a fairly large team and I need the options to work for cross-team compatibility.

Here are the two methods I've tried, neither of which worked. One where the latedef: 'nofunc' is added in the options, and another where it's set in a task specific object. Here they are:

``` javascript
module.exports = {
    options: {
        jshintrc: '.jshintrc',
        reporter: require('jshint-stylish'),
        latedef: 'nofunc'
    },
    scripts:  '<%= lintFiles %>'
};
```

``` javascript
module.exports = {
    options: {
        jshintrc: '.jshintrc',
        reporter: require('jshint-stylish')
    },
    scripts: {
        options: {
            latedef: 'nofunc'
        },
        src: '<%= lintFiles %>'
    }
};
```

**Comment by vkadam** [comment]
Seeing the same issue even with latedef: true is complains when var is defined later and used first

**Comment by juanpablof** [comment]
Same issue. I've temporary resolved it using //jshint latedef: nofunc

**Comment by ves-krd** [comment]
@wlanni How did you update the .jshintrc?

I tried `"latedef" : "nofunc"`, doesn't have any effect.

**Comment by juanpablof** [comment]
@ves-krd This is currently my .jshint file:

{
  "bitwise": true,
  "browser": true,
  "curly": true,
  "eqeqeq": true,
  "esnext": true,
  "latedef": "nofunc",
  "noarg": true,
  "node": true,
  "strict": true,
  "undef": true,
  "unused": true,
  "globals": {
    "angular": false
  }
}

if that doesn't work, try adding the following comment to your js files //jshint latedef: nofunc
It's not ideal, but it will buy you time until a solution to this problem is found.

**Comment by ves-krd** [comment]
@juanpablof Thanks!

**Comment by ravi4022** [comment]
your sample jshintrc file helps a lot... Thank you
